function [BW,maskedRGBImage] = board_ball_mask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 05-Oct-2021
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.000;
channel1Max = 1.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.000;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.000;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

% Create mask based on selected regions of interest on point cloud projection
I = double(I);
[m,n,~] = size(I);
polyBW = false([m,n]);
I = reshape(I,[m*n 3]);

% Convert HSV color space to canonical coordinates
Xcoord = I(:,2).*I(:,3).*cos(2*pi*I(:,1));
Ycoord = I(:,2).*I(:,3).*sin(2*pi*I(:,1));
I(:,1) = Xcoord;
I(:,2) = Ycoord;
clear Xcoord Ycoord

% Project 3D data into 2D projected view from current camera view point within app
J = rotateColorSpace(I);

% Apply polygons drawn on point cloud in app
polyBW = applyPolygons(J,polyBW);

% Combine both masks
BW = sliderBW & polyBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end

function J = rotateColorSpace(I)

% Translate the data to the mean of the current image within app
shiftVec = [0.010292 -0.012864 0.410044];
I = I - shiftVec;
I = [I ones(size(I,1),1)]';

% Apply transformation matrix
tMat = [0.597374 -0.759477 0.000000 0.061424;
    0.692771 0.620864 0.193197 -0.799865;
    0.162192 0.145357 -0.825207 8.986510;
    0.000000 0.000000 0.000000 1.000000];

J = (tMat*I)';
end

function polyBW = applyPolygons(J,polyBW)

% Define each manually generated ROI
hPoints(1).data = [-0.164500 -0.244857;
    -0.094337 -0.352127;
    -0.043820 -0.543349;
    -0.156080 -0.478053;
    -0.223436 -0.324144];

% Define each manually generated ROI
hPoints(2).data = [-0.074691 -0.160906;
    0.001084 -0.305488;
    0.009504 -0.459398;
    -0.001722 -0.548013;
    -0.055046 -0.436078;
    -0.091530 -0.258848];

% Define each manually generated ROI
hPoints(3).data = [0.152636 -0.090947;
    0.186314 -0.207545;
    0.205960 -0.333471;
    0.158249 -0.464062;
    0.090893 -0.492045;
    0.085280 -0.230865];

% Define each manually generated ROI
hPoints(4).data = [0.203153 -0.585324;
    0.340672 -0.468726;
    0.360318 -0.562004;
    0.211573 -0.725242;
    0.169475 -0.613308];

% Define each manually generated ROI
hPoints(5).data = [0.017923 -0.608644;
    0.071247 -0.683267;
    0.090893 -0.841841;
    0.079667 -1.023734;
    -0.063465 -0.972431;
    -0.035400 -0.757890];

% Iteratively apply each ROI
for ii = 1:length(hPoints)
    if size(hPoints(ii).data,1) > 2
        in = inpolygon(J(:,1),J(:,2),hPoints(ii).data(:,1),hPoints(ii).data(:,2));
        in = reshape(in,size(polyBW));
        polyBW = polyBW | in;
    end
end

end
